from django.core.management.base import BaseCommand, CommandError
from server.models import *

class Command(BaseCommand):
    args = 'autogenerated course params, room id'
    help = 'set a courses\'s classroom to a particular room'

    def handle(self, *args, **options):
        if len(args) < 2:
            print 'Missing arguments'
            return

        course_params = args[0].split(',')
        room_id = int(args[1])

        course = Course.objects.get(
            term__term_id=int(course_params[0]),
            subject=course_params[1],
            catalog_num=course_params[2],
            section=course_params[3])
        room = Room.objects.get(id=room_id)

        course.room = room
        course.save()
        print 'Success'
